### ISSUE TITLE
天啊 //@朴灵:这种李彦宏死几次都不够 //@XiNGRZ:唉 //@zhaochengw: 家属要求按照百度搜索的结果进行治疗我操你妈

### ISSUE THREAD

**Issue by zhangmengxue** [zhangmengxue/weibo#110]
<img> &#22825;&#21834; //@&#26420;&#28789;:&#36825;&#31181;&#26446;&#24422;&#23439;&#27515;&#20960;&#27425;&#37117;&#19981;&#22815; //@XiNGRZ:&#21769; //@zhaochengw: &#23478;&#23646;&#35201;&#27714;&#25353;&#29031;&#30334;&#24230;&#25628;&#32034;&#30340;&#32467;&#26524;&#36827;&#34892;&#27835;&#30103;&#65281;&#25105;&#25805;&#20320;&#22920;&#65281;<br>
@create:November 22, 2016 at 11:39PM<br>
via Weibo @link: http://ift.tt/2gcJWHL

**Comment by xingrz** [comment]
what…
